# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beb656e362c7a1d2f4e77654e1cca1174277f9684f2e22a34191569868986c9f6e3f17780f984637faffebc2026b098cae5cbbe604d92644e594653ac2f575de

test:
  secret_key_base: 0ab1b5224079bbfb190923c0ba9a593770958e9959fef0c4d244cd58f69bb888541eab689b2148452a6e75d3bfecc21c5c13649b247f56819f9063a3424c9bff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
